server:
  error:
    whitelabel:
      enabled: false
  port: 8090
  servlet:
    context-path: /
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: Kjb@llh2020
    keyStoreType: PKCS12
    keyAlias: tomcat
spring:
  mvc:
    servlet:
      path: /
    view:
      prefix: /page/
      suffix: .html

